webtalk_init -webtalk_dir D:/TCNJ/Academics/Courses/Senior_Year/Senior Project/TJT/Simulation/tjt_verify/tjt_verify.sim/sim_1/behav/xsim/xsim.dir/dlc_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar  2 13:52:28 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211580914_0_0_943" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "23d5f094-7081-4b77-84d2-2d119848f609" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "93f8638ee34c45a08c88f342e9794336" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5792_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2580588394 -regid "211580914_0_0_943" -xml D:/TCNJ/Academics/Courses/Senior_Year/Senior Project/TJT/Simulation/tjt_verify/tjt_verify.sim/sim_1/behav/xsim/xsim.dir/dlc_test_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/TCNJ/Academics/Courses/Senior_Year/Senior Project/TJT/Simulation/tjt_verify/tjt_verify.sim/sim_1/behav/xsim/xsim.dir/dlc_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/TCNJ/Academics/Courses/Senior_Year/Senior Project/TJT/Simulation/tjt_verify/tjt_verify.sim/sim_1/behav/xsim/xsim.dir/dlc_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
